EdmondFrank/compass-project-template

organizations/EAF-new.yml, single-projects/gitee/jfinal/jfinal.yml
=> Updated organizations/EAF-new.yml

single-projects/gitee/jfinal/jfinal.yml
=> Updated single-projects/gitee/jfinal/jfinal.yml

single-projects/github/emacs-eaf/eaf-git.yml
=> Updated single-projects/github/emacs-eaf/eaf-git.yml

single-projects/github/EdmondFrank/.emacs.d.yml
=> Updated single-projects/github/EdmondFrank/.emacs.d.yml

single-projects/github/elixir-crawly/crawly.yml
=> Updated single-projects/github/elixir-crawly/crawly.yml

single-projects/github/elixirprogrammer/InstagramClonePETAL.yml
=> Updated single-projects/github/elixirprogrammer/InstagramClonePETAL.yml

single-projects/github/frei-x/ChineseChessOnline.yml
=> Updated single-projects/github/frei-x/ChineseChessOnline.yml

single-projects/github/bytebase/bytebase.yml
=> Updated single-projects/github/bytebase/bytebase.yml

organizations/emacs-eaf.yml
=> Updated organizations/emacs-eaf.yml

single-projects/github/phoenixframework/phoenix.yml
=> Updated single-projects/github/phoenixframework/phoenix.yml

single-projects/github/ant-design/ant-design.yml
=> Updated single-projects/github/ant-design/ant-design.yml

single-projects/github/Shopify/hydrogen-ui.yml
=> Updated single-projects/github/Shopify/hydrogen-ui.yml

single-projects/github/chaoss/grimoirelab.yml
=> Updated single-projects/github/chaoss/grimoirelab.yml

single-projects/github/uptrace/bun.yml
=> Updated single-projects/github/uptrace/bun.yml

single-repositories/github/EdmondFrank/blink-search.yml
=> Updated single-repositories/github/EdmondFrank/blink-search.yml

communities/.emacs.d.yml
=> Updated communities/.emacs.d.yml

single-repositories/github/EdmondFrank/rocketmq-client-ruby.yml
submitted by @EdmondFrank, repository: https://github.com/EdmondFrank/rocketmq-client-ruby
=> Updated single-repositories/github/EdmondFrank/rocketmq-client-ruby.yml

single-repositories/github/emqx/quic.yml
submitted by @EdmondFrank, repository: https://github.com/emqx/quic
=> Updated single-repositories/github/emqx/quic.yml

communities/emqx.yml
=> Updated communities/emqx.yml

single-repositories/github/jondot/sneakers.yml
submitted by @EdmondFrank, repository: https://github.com/jondot/sneakers
=> Updated single-repositories/github/jondot/sneakers.yml

communities/neovim.yml
=> Updated communities/neovim.yml

communities/winget-pkgs.yml
=> Updated communities/winget-pkgs.yml

single-repositories/github/lorniu/go-translate.yml
submitted by @EdmondFrank, repository: https://github.com/lorniu/go-translate
=> Updated single-repositories/github/lorniu/go-translate.yml

single-repositories/github/swoosh/swoosh.yml
submitted by @EdmondFrank, repository: https://github.com/swoosh/swoosh
=> Updated single-repositories/github/swoosh/swoosh.yml

single-repositories/github/atykhonov/google-translate.yml
submitted by @EdmondFrank, repository: https://github.com/atykhonov/google-translate
=> Updated single-repositories/github/atykhonov/google-translate.yml

single-repositories/github/lujun9972/emacs-document.yml
submitted by @EdmondFrank, repository: https://github.com/lujun9972/emacs-document
=> Updated single-repositories/github/lujun9972/emacs-document.yml

single-repositories/github/oss-compass/compass-web.yml
submitted by @nanzm, repository: https://github.com/oss-compass/compass-web
=> Updated single-repositories/github/oss-compass/compass-web.yml

single-repositories/github/zema1/suo5.yml
submitted by @weihongbin1, repository: https://github.com/zema1/suo5
=> Updated single-repositories/github/zema1/suo5.yml

single-repositories/github/EdmondFrank/tramp.yml
submitted by @EdmondFrank, repository: https://github.com/EdmondFrank/tramp
=> Updated single-repositories/github/EdmondFrank/tramp.yml

single-repositories/github/EdmondFrank/rHyperion1.x.yml
submitted by @EdmondFrank, repository: https://github.com/EdmondFrank/rHyperion1.x
=> Updated single-repositories/github/EdmondFrank/rHyperion1.x.yml

communities/nanzm.yml
=> Updated communities/nanzm.yml

single-repositories/github/flomesh-io/pipy.yml
submitted by @EdmondFrank, repository: https://github.com/flomesh-io/pipy
=> Updated single-repositories/github/flomesh-io/pipy.yml

communities/oss-compass.yml
=> Updated communities/oss-compass.yml

communities/flomesh-io.yml
=> Updated communities/flomesh-io.yml

communities/main-flomesh-io.yml
=> Updated communities/main-flomesh-io.yml

communities/ByConity.yml
=> Updated communities/ByConity.yml

communities/radian-software.yml
=> Updated communities/radian-software.yml

single-repositories/github/oss-compass/compass-web-service.yml
=> Updated single-repositories/github/oss-compass/compass-web-service.yml developers

single-repositories/github/oss-compass/compass-web.yml
=> Updated single-repositories/github/oss-compass/compass-web.yml developers

single-repositories/github/oss-compass/community.yml
=> Updated single-repositories/github/oss-compass/community.yml developers
